// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsrzcsnBIDuNxHLT3K5cBGJiNLX593-PE',
    appId: '1:132704276288:web:dddd7ffa8912aee7f334a5',
    messagingSenderId: '132704276288',
    projectId: 'upa-kerjasama-a8f07',
    authDomain: 'upa-kerjasama-a8f07.firebaseapp.com',
    storageBucket: 'upa-kerjasama-a8f07.firebasestorage.app',
    measurementId: 'G-GPRK9N182W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrZEYyWIPyZurcg2s1iev7Smw7B-EWpXg',
    appId: '1:132704276288:android:8d4bc7a683071710f334a5',
    messagingSenderId: '132704276288',
    projectId: 'upa-kerjasama-a8f07',
    storageBucket: 'upa-kerjasama-a8f07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXikolp8tfVFB1iQ-UCNQjd0tFYrznbLE',
    appId: '1:132704276288:ios:ced2fc012584b94ef334a5',
    messagingSenderId: '132704276288',
    projectId: 'upa-kerjasama-a8f07',
    storageBucket: 'upa-kerjasama-a8f07.firebasestorage.app',
    iosBundleId: 'com.example.upaKerjasamaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXikolp8tfVFB1iQ-UCNQjd0tFYrznbLE',
    appId: '1:132704276288:ios:ced2fc012584b94ef334a5',
    messagingSenderId: '132704276288',
    projectId: 'upa-kerjasama-a8f07',
    storageBucket: 'upa-kerjasama-a8f07.firebasestorage.app',
    iosBundleId: 'com.example.upaKerjasamaMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsrzcsnBIDuNxHLT3K5cBGJiNLX593-PE',
    appId: '1:132704276288:web:c122be25e318f117f334a5',
    messagingSenderId: '132704276288',
    projectId: 'upa-kerjasama-a8f07',
    authDomain: 'upa-kerjasama-a8f07.firebaseapp.com',
    storageBucket: 'upa-kerjasama-a8f07.firebasestorage.app',
    measurementId: 'G-WZ4HXXMHVX',
  );
}
